# Site settings
title: Jekyll-Uno
description: 'Jekyll-Uno - a minimal, responsive theme for Jekyll'
url: 'https://helllth.github.io/' 
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'

author:
  name: 'Thorsten Hell'
  email: th@cismet.de
  twitter_username: helllth
  github_username:  helllth
  linkedin_username:  thorstenhell

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']

gems:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
